force-app/main/default/objects/BBC_Article__c/BBC_Article__c.object-meta.xml
<CustomObject>
    <label>BBC Article</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>BBC Articles Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BBC Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BBC_Article__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BBC_Article__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title of the Article</description>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BBC_Article__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>URL of the article</description>
    <label>URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/Utilities/TestDataFactory.cls
@IsTest
public class TestDataFactory {

    public static void createBBCArticles(Integer count) {
        List<BBC_Article__c> articles = new List<BBC_Article__c>();

        for (Integer i = 1; i <= count; i++) {
            articles.add(new BBC_Article__c(
                Title__c = 'Article ' + i,
                URL__c = 'https://www.example.com/article' + i,
                Rank__c = i
            ));
        }
        insert articles;
    }

    public static User createRestrictedUser() {
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        Id roleId = [SELECT Id FROM UserRole LIMIT 1].Id; 

        User restrictedUser = new User(
            ProfileId = profile.Id,
            UserRoleId = roleId,
            Username = 'restricteduser' + Math.random() + '@test.com',
            Email = 'restricteduser' + Math.random() + '@test.com',
            LastName = 'Restricted',
            Alias = 'restr' + String.valueOf(Math.round(Math.random() * 100)),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
        );
        insert restrictedUser;
        return restrictedUser;
    }
    
    public static User createPermittedUser() {
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        Id roleId = [SELECT Id FROM UserRole LIMIT 1].Id; 

        User allowedUser = new User(
            ProfileId = profile.Id,
            UserRoleId = roleId,
            Username = 'alloweduser' + Math.random() + '@test.com',
            Email = 'alloweduser' + Math.random() + '@test.com',
            LastName = 'Allowed',
            Alias = 'allow' + String.valueOf(Math.round(Math.random() * 100)),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
        );
        insert allowedUser;

        
        PermissionSet permissionSet = [SELECT Id FROM PermissionSet WHERE Name = 'Sales_Manager' LIMIT 1];
        insert new PermissionSetAssignment(
            AssigneeId = allowedUser.Id,
            PermissionSetId = permissionSet.Id
        );

        return allowedUser;
    }
}